"use client";
import { ChangeEvent, useState } from "react";
import ResultCard from "@/components/ResultCard";
import PricingSection from "@/components/PricingSection";
import AuthModal from "@/components/AuthModal";
import type { AnalysisResult } from "@/lib/analysis";

const copy = {
  en: { nav:["How it works","Features","Pricing"], sign:"Sign in", hero:"Build a resume that gets noticed.", sub:"Upload your PDF or DOCX and receive a practical, job-specific ATS report in minutes.", cta:"Analyze my resume", title:"Professional resume analysis", resume:"Resume text", job:"Target job description (optional)", upload:"Upload PDF or DOCX", analyze:"Start analysis", working:"Analyzing…", report:"Your resume report", download:"Download PDF", saved:"Signed-in reports are saved automatically." },
  ar: { nav:["كيف يعمل","المميزات","الأسعار"], sign:"تسجيل الدخول", hero:"سيرة ذاتية تلفت الانتباه.", sub:"ارفع ملف PDF أو DOCX واحصل خلال دقائق على تقرير احترافي متوافق مع أنظمة ATS.", cta:"حلّل سيرتي الذاتية", title:"تحليل احترافي للسيرة الذاتية", resume:"نص السيرة الذاتية", job:"الوصف الوظيفي المستهدف (اختياري)", upload:"رفع PDF أو DOCX", analyze:"ابدأ التحليل", working:"جارٍ التحليل…", report:"تقرير سيرتك الذاتية", download:"تنزيل PDF", saved:"تُحفظ تقارير المستخدم المسجل تلقائيًا." }
};

export default function Home() {
  const [locale,setLocale]=useState<"en"|"ar">("en"); const t=copy[locale]; const ar=locale==="ar";
  const [resumeText,setResumeText]=useState(""); const [jobDescription,setJobDescription]=useState(""); const [result,setResult]=useState<AnalysisResult|null>(null); const [loading,setLoading]=useState(false); const [uploading,setUploading]=useState(false); const [error,setError]=useState(""); const [auth,setAuth]=useState(false);
  async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setUploading(true);setError("");const form=new FormData();form.append("file",file);const res=await fetch("/api/upload",{method:"POST",body:form});const data=await res.json();if(res.ok)setResumeText(data.text);else setError(data.error);setUploading(false)}
  async function analyze(){if(resumeText.trim().length<50)return;setLoading(true);setError("");const res=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resumeText,jobDescription,locale})});const data=await res.json();if(res.ok){setResult(data);await fetch("/api/analyses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:jobDescription.slice(0,80)||"Resume analysis",result:data})})}else setError(data.error);setLoading(false)}
  async function download(){if(!result)return;const {jsPDF}=await import("jspdf");const doc=new jsPDF();doc.setFontSize(20);doc.text("ResumeCheck Report",20,22);doc.setFontSize(12);doc.text(`Overall: ${result.overallScore}/100   ATS: ${result.atsCompatibility.score}/100`,20,34);const lines=doc.splitTextToSize(result.summary,170);doc.text(lines,20,46);let y=46+lines.length*6+8;doc.setFontSize(15);doc.text("Strengths",20,y);y+=8;doc.setFontSize(10);result.strengths.forEach(x=>{const l=doc.splitTextToSize(`• ${x}`,165);if(y>275){doc.addPage();y=20}doc.text(l,22,y);y+=l.length*5+2});doc.save("resumecheck-report.pdf")}
  return <div dir={ar?"rtl":"ltr"} className="min-h-screen bg-white"><AuthModal open={auth} onClose={()=>setAuth(false)} locale={locale}/><header className="fixed inset-x-0 top-0 z-50 border-b bg-white/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><a href="#" className="text-xl font-black text-indigo-600">✓ ResumeCheck</a><nav className="hidden gap-7 text-sm font-semibold md:flex"><a href="#how">{t.nav[0]}</a><a href="#features">{t.nav[1]}</a><a href="#pricing">{t.nav[2]}</a><a href="/dashboard">Dashboard</a></nav><div className="flex gap-2"><button onClick={()=>setLocale(ar?"en":"ar")} className="rounded-lg border px-3 py-2 text-sm font-bold">{ar?"EN":"العربية"}</button><button onClick={()=>setAuth(true)} className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white">{t.sign}</button></div></div></header>
  <main><section className="bg-gradient-to-b from-indigo-50 pt-36 pb-24"><div className="mx-auto max-w-5xl px-5 text-center"><span className="rounded-full border bg-white px-4 py-2 text-xs font-bold text-indigo-700">AI + ATS RESUME REVIEW</span><h1 className="mx-auto mt-7 max-w-4xl text-5xl font-black tracking-tight sm:text-7xl">{t.hero}</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600">{t.sub}</p><a href="#analyzer" className="mt-8 inline-block rounded-xl bg-indigo-600 px-7 py-4 font-bold text-white shadow-xl shadow-indigo-200">{t.cta}</a></div></section>
  <section id="how" className="border-y bg-slate-50 py-20"><div className="mx-auto grid max-w-6xl gap-6 px-5 md:grid-cols-3">{(ar?[["1","ارفع سيرتك","PDF أو DOCX أو نص مباشر"],["2","أضف الوظيفة","لتحليل مخصص ودقيق"],["3","احصل على الخطة","درجات وأولويات وتوصيات"]]:[["1","Upload your resume","PDF, DOCX, or pasted text"],["2","Add the target role","For precise keyword matching"],["3","Receive your plan","Scores, priorities, and recommendations"]]).map(x=><article key={x[0]} className="rounded-3xl border bg-white p-7"><b className="text-indigo-600">{x[0]}</b><h2 className="mt-8 text-xl font-bold">{x[1]}</h2><p className="mt-2 text-slate-600">{x[2]}</p></article>)}</div></section>
  <section id="analyzer" className="py-24"><div className="mx-auto max-w-5xl px-5"><h2 className="text-center text-4xl font-black">{t.title}</h2><div className="mt-10 rounded-3xl border bg-white p-6 shadow-soft sm:p-8">{!result&&<div className="grid gap-6 lg:grid-cols-2"><div><label className="font-bold">{t.resume}</label><textarea value={resumeText} onChange={e=>setResumeText(e.target.value.slice(0,20000))} rows={14} className="mt-2 w-full rounded-2xl border bg-slate-50 p-4"/><label className="mt-3 flex cursor-pointer items-center justify-center rounded-xl border-2 border-dashed p-4 text-sm font-bold text-indigo-600"><input className="hidden" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={upload}/>{uploading?"Reading document…":t.upload}</label></div><div><label className="font-bold">{t.job}</label><textarea value={jobDescription} onChange={e=>setJobDescription(e.target.value.slice(0,20000))} rows={11} className="mt-2 w-full rounded-2xl border bg-slate-50 p-4"/><p className="mt-3 rounded-xl bg-emerald-50 p-4 text-xs text-emerald-800">{t.saved}</p><button onClick={analyze} disabled={loading||resumeText.length<50} className="mt-4 w-full rounded-xl bg-indigo-600 p-4 font-bold text-white disabled:opacity-40">{loading?t.working:t.analyze}</button></div></div>}{error&&<p className="mt-4 rounded-xl bg-rose-50 p-4 text-rose-700">{error}</p>}{result&&<div><div className="mb-6 flex items-center justify-between"><h3 className="text-2xl font-bold">{t.report}</h3><button onClick={download} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white">{t.download}</button></div><ResultCard result={result} locale={locale}/><button onClick={()=>setResult(null)} className="mt-6 rounded-xl border px-5 py-3 font-bold">{ar?"تحليل جديد":"New analysis"}</button></div>}</div></div></section>
  <section id="features" className="bg-slate-50 py-20"><div className="mx-auto grid max-w-6xl gap-6 px-5 sm:grid-cols-2 lg:grid-cols-3">{(ar?["درجة ATS","مطابقة الكلمات","تحليل التأثير","اقتراحات عملية","تقارير محفوظة","تنزيل PDF"]:["ATS scoring","Keyword matching","Impact analysis","Actionable fixes","Saved reports","PDF export"]).map(x=><div key={x} className="rounded-2xl border bg-white p-6 font-bold">✓ {x}</div>)}</div></section><PricingSection/></main>
  <footer className="border-t bg-slate-950 text-white"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-5 px-5 py-10 sm:flex-row"><b>ResumeCheck</b><div className="flex gap-5 text-sm"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/contact">Contact</a></div><span className="text-sm text-slate-400">© {new Date().getFullYear()} ResumeCheck</span></div></footer></div>;
}
